# Generated by Django 4.2.7 on 2025-02-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mothers_hive'),
    ]

    operations = [
        migrations.AddField(
            model_name='hives',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hivesplaces',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mothers',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hives',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hivesplaces', unique=True),
        ),
        migrations.AddConstraint(
            model_name='hives',
            constraint=models.UniqueConstraint(fields=('place', 'number'), name='unique_place_hive_number'),
        ),
        migrations.AddConstraint(
            model_name='hivesplaces',
            constraint=models.UniqueConstraint(fields=('beekeeper', 'name'), name='unique_beekeeper_place_name'),
        ),
    ]
