# Generated by Django 4.2.7 on 2025-02-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_hives_place_alter_mothers_hive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hives',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='myapp.hivesplaces'),
        ),
        migrations.AlterField(
            model_name='mothers',
            name='hive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothers', to='myapp.hives'),
        ),
    ]
