# Generated by Django 4.2.7 on 2025-02-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_hives_place_alter_mothers_hive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='hive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='myapp.hives'),
        ),
    ]
