# Generated by Django 4.2.7 on 2025-02-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_visits_hive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hives',
            name='active',
        ),
    ]
