# Generated by Django 4.2.7 on 2025-02-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_hives_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hivesplaces',
            name='unique_beekeeper_place_name',
        ),
        migrations.AddConstraint(
            model_name='hivesplaces',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('beekeeper', 'name'), name='unique_active_beekeeper_place_name'),
        ),
    ]
