# Generated by Django 4.2.7 on 2025-02-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_hivesplaces_unique_beekeeper_place_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hives',
            name='unique_place_hive_number',
        ),
        migrations.AddConstraint(
            model_name='hives',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('place', 'number'), name='unique_place_hive_number'),
        ),
    ]
