# Generated by Django 4.2.7 on 2025-02-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_visits_condition_alter_visits_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='condition',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
