# Generated by Django 4.2.7 on 2025-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_visits_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hives',
            name='size',
        ),
        migrations.AlterField(
            model_name='visits',
            name='hive_body_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='honey_supers_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
