# Generated by Django 4.2.7 on 2025-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_hives_size_alter_visits_hive_body_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='hive_body_size',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visits',
            name='honey_supers_size',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
